@Announcement_api_HostAddress = https://localhost:7007

GET {{Announcement_api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Announcement_api_HostAddress}}/{id}

###

GET {{Announcement_api_HostAddress}}/{id}

###

GET {{Announcement_api_HostAddress}}/api/Announcement/

###
